export const data = [
  {
    id: 1,
    name: "users",
    columns: ["id", "username", "email", "created_at"],
    description: "Table containing user information",
    row: 1000,
    size: "10MB",
  },
  {
    id: 2,
    name: "orders",
    columns: ["id", "user_id", "product_id", "quantity", "status"],
    description: "Table containing order information",
    row: 5000,
    size: "25MB",
  },
  {
    id: 3,
    name: "products",
    columns: ["id", "name", "description", "price", "stock"],
    description: "Table containing product information",
    row: 200,
    size: "5MB",
  },
  {
    id: 4,
    name: "categories",
    columns: ["id", "name", "description"],
    description: "Table containing category information",
    row: 50,
    size: "1MB",
  },
  {
    id: 5,
    name: "customers",
    columns: ["id", "first_name", "last_name", "email", "phone"],
    description: "Table containing customer information",
    row: 1000,
    size: "8MB",
  },
  {
    id: 6,
    name: "inventory",
    columns: ["id", "product_id", "quantity"],
    description: "Table containing inventory information",
    row: 300,
    size: "2MB",
  },
  {
    id: 7,
    name: "sales",
    columns: ["id", "product_id", "amount", "sale_date"],
    description: "Table containing sales information",
    row: 2000,
    size: "15MB",
  },
  {
    id: 8,
    name: "employees",
    columns: ["id", "first_name", "last_name", "position", "salary"],
    description: "Table containing employee information",
    row: 100,
    size: "3MB",
  },
  {
    id: 9,
    name: "departments",
    columns: ["id", "name", "manager_id"],
    description: "Table containing department information",
    row: 10,
    size: "500KB",
  },
  {
    id: 10,
    name: "suppliers",
    columns: ["id", "name", "contact_info"],
    description: "Table containing supplier information",
    row: 50,
    size: "1MB",
  },
];
